"""Exports Steppie and the cast from steppie.py / cast.py into
ios/Steppie/DesignSystem/MascotArt.swift.

Run from this directory:  python3 export_swift.py
"""
import os
import cast
import steppie

EYE_GROUPS = ("eyeL", "eyeR", "eyes")


def hexcol(c):
    return "0x" + c.lstrip("#").upper()


def part(p):
    fill = hexcol(p["fill"]) if "fill" in p else "nil"
    stroke = hexcol(p["stroke"]) if "stroke" in p else "nil"
    return (f'.init("{p["id"]}", "{p["d"]}", fill: {fill}, stroke: {stroke}, '
            f'width: {p.get("width", 0)}, opacity: {p.get("opacity", 1)})')


DECLS = []


def arr(ps, name):
    """Declares a typed static array (keeps the type checker fast) and returns its name."""
    body = "[]" if not ps else "[\n" + "".join(f"        {part(p)},\n" for p in ps) + "    ]"
    DECLS.append(f"    private static let {name}: [Part] = {body}\n")
    return name


def pt(p):
    return f"CGPoint(x: {p[0]}, y: {p[1]})"


def by(ps, *groups):
    return [p for p in ps if p["group"] in groups]


def moods_dict(build, moods, groups, name):
    items = [f'"{m}": {arr(by(build(m), *groups), f"{name}_{m}")}' for m in moods]
    DECLS.append(f"    private static let {name}: [String: [Part]] = [" + ", ".join(items) + "]\n")
    return name


out = ['''// Generated by brand/mascot/tools/export_swift.py from steppie.py and cast.py. Do not edit by hand.
// Steppie and the cast: vector parts in a 400 x 460 unit canvas (y down), grouped by rig bone.
import CoreGraphics

enum MascotArt {
    struct Part: Sendable {
        let id: String
        let d: String
        let fill: UInt32?
        let stroke: UInt32?
        let width: CGFloat
        let opacity: Double

        init(_ id: String, _ d: String, fill: UInt32?, stroke: UInt32?, width: CGFloat, opacity: Double) {
            self.id = id; self.d = d; self.fill = fill; self.stroke = stroke; self.width = width; self.opacity = opacity
        }
    }

    /// One character: parts per bone, pivots, and per-mood face parts.
    struct Rig: Sendable {
        let neck: CGPoint
        let shoulderL: CGPoint
        let shoulderR: CGPoint
        let hipL: CGPoint
        let hipR: CGPoint
        let tailBase: CGPoint
        let eyeY: CGFloat
        let shadow: [Part]
        let tail: [Part]
        let legL: [Part]
        let legR: [Part]
        let body: [Part]
        let armL: [Part]
        let armR: [Part]
        let head: [Part]
        /// Steppie only: mane by level (cub → king). Empty for the cast.
        let manes: [[Part]]
        let eyes: [String: [Part]]
        let brows: [String: [Part]]
        let mouth: [String: [Part]]
    }

    static let canvas = CGSize(width: 400, height: 460)
''']

# Steppie --------------------------------------------------------------------
base = steppie.parts("happy", "idle", 2)
manes = [by(steppie.parts("happy", "idle", lvl), "mane") for lvl in sorted(steppie.MANE_LEVELS)]
mane_src = "[" + ", ".join(arr(m, f"steppie_mane{i}") for i, m in enumerate(manes)) + "]"
out.append(f'''
    static let steppie = Rig(
        neck: {pt(steppie.NECK)}, shoulderL: {pt(steppie.SHOULDER_L)}, shoulderR: {pt(steppie.SHOULDER_R)},
        hipL: {pt(steppie.HIP_L)}, hipR: {pt(steppie.HIP_R)}, tailBase: {pt(steppie.TAIL_BASE)}, eyeY: {steppie.EYE_Y:.1f},
        shadow: {arr(by(base, "shadow"), "steppie_shadow")},
        tail: {arr(by(base, "tail"), "steppie_tail")},
        legL: {arr(by(base, "legL"), "steppie_legL")},
        legR: {arr(by(base, "legR"), "steppie_legR")},
        body: {arr(by(base, "body"), "steppie_body")},
        armL: {arr(by(base, "armL"), "steppie_armL")},
        armR: {arr(by(base, "armR"), "steppie_armR")},
        head: {arr(by(base, "head"), "steppie_head")},
        manes: {mane_src},
        eyes: {moods_dict(lambda m: steppie.parts(m, "idle", 2), steppie.MOODS, EYE_GROUPS, "steppie_eyes")},
        brows: {moods_dict(lambda m: steppie.parts(m, "idle", 2), steppie.MOODS, ("brows",), "steppie_brows")},
        mouth: {moods_dict(lambda m: steppie.parts(m, "idle", 2), steppie.MOODS, ("mouth",), "steppie_mouth")}
    )
''')

# Cast ------------------------------------------------------------------------
for who in cast.CAST:
    build = cast.BUILDERS[who]
    pv = cast.PIVOTS[who]
    ps = build("happy")
    out.append(f'''
    static let {who} = Rig(
        neck: {pt(pv["neck"])}, shoulderL: {pt(pv["shoulderL"])}, shoulderR: {pt(pv["shoulderR"])},
        hipL: {pt(pv["hipL"])}, hipR: {pt(pv["hipR"])}, tailBase: {pt(pv["tail"])}, eyeY: {pv["eyeY"]},
        shadow: {arr(by(ps, "shadow"), f"{who}_shadow")},
        tail: {arr(by(ps, "tail"), f"{who}_tail")},
        legL: {arr(by(ps, "legL"), f"{who}_legL")},
        legR: {arr(by(ps, "legR"), f"{who}_legR")},
        body: {arr(by(ps, "body"), f"{who}_body")},
        armL: {arr(by(ps, "armL"), f"{who}_armL")},
        armR: {arr(by(ps, "armR"), f"{who}_armR")},
        head: {arr(by(ps, "head"), f"{who}_head")},
        manes: [],
        eyes: {moods_dict(build, cast.MOODS, EYE_GROUPS, f"{who}_eyes")},
        brows: {moods_dict(build, cast.MOODS, ("brows",), f"{who}_brows")},
        mouth: {moods_dict(build, cast.MOODS, ("mouth",), f"{who}_mouth")}
    )
''')

out.append("\n    /// Arm rotations in degrees (clockwise-positive), left then right.\n")
out.append("    static func arms(_ pose: String) -> (Double, Double) {\n        switch pose {\n")
for pose in steppie.POSES:
    l, r = steppie.arm_rotations(pose)
    out.append(f'        case "{pose}": return ({l}, {r})\n')
out.append("        default: return (0, 0)\n        }\n    }\n\n")
out.extend(DECLS)
out.append("}\n")

dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../ios/Steppie/DesignSystem/MascotArt.swift")
src = "".join(out)
open(dest, "w").write(src)
print("wrote", os.path.normpath(dest), len(src), "bytes")
