"""Exports Grin's geometry from grin.py into ios/Grinda/DesignSystem/MascotArt.swift.

Run from this directory:  python3 export_swift.py
"""
import os
import grin

MOODS = ["happy", "calm", "cheer", "roar", "worried", "sleep", "wink", "proud"]
FACE_GROUPS = ("eyeL", "eyeR", "eyes", "brows", "mouth")
MANE_IDS = ("maneBack", "mane", "maneLight")


def hexcol(c):
    return "0x" + c.lstrip("#").upper()


def part(p):
    fill = hexcol(p["fill"]) if "fill" in p else "nil"
    stroke = hexcol(p["stroke"]) if "stroke" in p else "nil"
    width = p.get("width", 0)
    op = p.get("opacity", 1)
    butt = "true" if p["id"] == "bibMark" else "false"
    return f'.init("{p["d"]}", fill: {fill}, stroke: {stroke}, width: {width}, opacity: {op}, butt: {butt})'


def block(name, ps, indent="    "):
    inner = (",\n" + indent * 2).join(part(p) for p in ps)
    return f"{indent}static let {name}: [Part] = [\n{indent*2}{inner},\n{indent}]\n"


base = grin.parts("happy", "idle", 2)
by_group = lambda ps, g: [p for p in ps if p["group"] == g]

out = ['''// Generated by brand/mascot/tools/export_swift.py from grin.py. Do not edit by hand.
// Grin, the Grinda lion: vector parts in a 400 x 460 unit canvas (y down).
import CoreGraphics

enum MascotArt {
    struct Part {
        let d: String
        let fill: UInt32?
        let stroke: UInt32?
        let width: CGFloat
        let opacity: Double
        let butt: Bool

        init(_ d: String, fill: UInt32?, stroke: UInt32?, width: CGFloat, opacity: Double, butt: Bool) {
            self.d = d; self.fill = fill; self.stroke = stroke; self.width = width; self.opacity = opacity; self.butt = butt
        }
    }

    static let canvas = CGSize(width: 400, height: 460)
''']
out.append(f"    static let neck = CGPoint(x: {grin.NECK[0]}, y: {grin.NECK[1]})\n")
out.append(f"    static let shoulderL = CGPoint(x: {grin.SHOULDER_L[0]}, y: {grin.SHOULDER_L[1]})\n")
out.append(f"    static let shoulderR = CGPoint(x: {grin.SHOULDER_R[0]}, y: {grin.SHOULDER_R[1]})\n")
out.append(f"    static let tailBase = CGPoint(x: {grin.TAIL_BASE[0]}, y: {grin.TAIL_BASE[1]})\n")
out.append(f"    static let eyeLine = CGPoint(x: 200, y: {grin.EYE_L[1]})\n\n")

out.append(block("tail", by_group(base, "tail")))
out.append(block("body", by_group(base, "body")))
out.append(block("armL", by_group(base, "armL")))
out.append(block("armR", by_group(base, "armR")))
out.append(block("head", [p for p in by_group(base, "head") if p["id"] not in MANE_IDS]))

for lvl in sorted(grin.MANE_LEVELS):
    ps = [p for p in grin.parts("happy", "idle", lvl) if p["id"] in MANE_IDS]
    out.append(block(f"mane{lvl}", ps))
out.append("    static let manes: [[Part]] = [mane0, mane1, mane2, mane3]\n\n")

for mood in MOODS:
    ps = grin.parts(mood, "idle", 2)
    eyes = [p for p in ps if p["group"] in ("eyeL", "eyeR", "eyes")]
    out.append(block(f"eyes_{mood}", eyes))
    out.append(block(f"brows_{mood}", by_group(ps, "brows")))
    out.append(block(f"mouth_{mood}", by_group(ps, "mouth")))

out.append("    static func eyes(_ mood: String) -> [Part] {\n        switch mood {\n")
for mood in MOODS:
    out.append(f'        case "{mood}": return eyes_{mood}\n')
out.append("        default: return eyes_happy\n        }\n    }\n\n")
out.append("    static func brows(_ mood: String) -> [Part] {\n        switch mood {\n")
for mood in MOODS:
    out.append(f'        case "{mood}": return brows_{mood}\n')
out.append("        default: return brows_happy\n        }\n    }\n\n")
out.append("    static func mouth(_ mood: String) -> [Part] {\n        switch mood {\n")
for mood in MOODS:
    out.append(f'        case "{mood}": return mouth_{mood}\n')
out.append("        default: return mouth_happy\n        }\n    }\n")

poses = ["idle", "cheer", "wave", "hold", "flex"]
out.append("\n    /// Arm rotations in degrees (clockwise-positive), left then right.\n")
out.append("    static func arms(_ pose: String) -> (Double, Double) {\n        switch pose {\n")
for pose in poses:
    l, r = grin.arm_rotations(pose)
    out.append(f'        case "{pose}": return ({l}, {r})\n')
out.append("        default: return (0, 0)\n        }\n    }\n}\n")

dest = os.path.join(os.path.dirname(__file__), "../../../ios/Grinda/DesignSystem/MascotArt.swift")
open(dest, "w").write("".join(out))
print("wrote", os.path.normpath(dest), sum(len(x) for x in out), "bytes")
